import React from "react";

export const POST_REQUEST_DATA = "POST_REQUEST_DATA";
export const POST_SUCCESS_DATA = "POST_SUCCESS_DATA";
export const POST_FAIL_DATA = "POST_FAIL_DATA";

export const BLOG_REQUEST_DATA = "BLOG_REQUEST_DATA";
export const BLOG_SUCCESS_DATA = "BLOG_SUCCESS_DATA";
export const BLOG_FAIL_DATA = "BLOG_FAIL_DATA";

export const BLOG_REQUEST_ADD = "BLOG_REQUEST_ADD";
export const BLOG_SUCCESS_ADD = "BLOG_SUCCESS_ADD";
export const BLOG_FAIL_ADD = "BLOG_FAIL_ADD";

export const BLOG_REQUEST_UPDATE = "BLOG_REQUEST_UPDATE";
export const BLOG_SUCCESS_UPDATE = "BLOG_SUCCESS_UPDATE";
export const BLOG_FAIL_UPDATE = "BLOG_FAIL_UPDATE";

export const BLOG_REQUEST_DELETE = "BLOG_REQUEST_DELETE";
export const BLOG_SUCCESS_DELETE = "BLOG_SUCCESS_DELETE";
export const BLOG_FAIL_DELETE = "BLOG_FAIL_DELETE";

export const BLOG_SINGLE_USER_REQUEST = "BLOG_SINGLE_USER_REQUEST";
export const BLOG_SINGLE_USER_SUCCESS = "BLOG_SINGLE_USER_SUCCESS";
export const BLOG_SINGLE_USER_FAIL = "BLOG_SINGLE_USER_FAIL";

export const ActionTypes = {
  UPDATE_USER: "UPDATE_USER",
  GET_USER: " GET_USER",
  GET_USERS: "GET_USERS",
  ADD_USER: " ADD_USER",
  DELETE_USER: "DELETE_USER",
};
